### ISSUE TITLE
Recompile is slow

### ISSUE THREAD

**Issue by tinkerbaj** [boussadjra/vitesse-react#1]
In many cases when I change some parts it takes up to 15 seconds to remove all errors and start work. Do you know what cause this is there maybe some of the recommended plugins?

**Comment by boussadjra** [comment]
I didn't notice this issue when I was developing  this template, I'll check it again and see the source of this issue

**Comment by tinkerbaj** [comment]
I create for myself something almost the same with dynamic routing from scratch in a few lines https://github.com/tinkerbaj/react-vite-typescript-autorouting/ I will try to compare it and see if I can notice a difference or maybe it is because of plugins.
